spring.application.name=sphere-d

server.port=5001

spring.datasource.url=jdbc:postgresql://localhost:5432/d_sphere_db
spring.datasource.username=vaibhav.singhal
spring.datasource.password=psql

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always